//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ttpim.gamemodule.database
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LottoDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LottoDBEntities object using the connection string found in the 'LottoDBEntities' section of the application configuration file.
        /// </summary>
        public LottoDBEntities() : base("name=LottoDBEntities", "LottoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LottoDBEntities object.
        /// </summary>
        public LottoDBEntities(string connectionString) : base(connectionString, "LottoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LottoDBEntities object.
        /// </summary>
        public LottoDBEntities(EntityConnection connection) : base(connection, "LottoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Archive> Archives
        {
            get
            {
                if ((_Archives == null))
                {
                    _Archives = base.CreateObjectSet<Archive>("Archives");
                }
                return _Archives;
            }
        }
        private ObjectSet<Archive> _Archives;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Board> Boards
        {
            get
            {
                if ((_Boards == null))
                {
                    _Boards = base.CreateObjectSet<Board>("Boards");
                }
                return _Boards;
            }
        }
        private ObjectSet<Board> _Boards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setup> Setups
        {
            get
            {
                if ((_Setups == null))
                {
                    _Setups = base.CreateObjectSet<Setup>("Setups");
                }
                return _Setups;
            }
        }
        private ObjectSet<Setup> _Setups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subscription> Subscriptions
        {
            get
            {
                if ((_Subscriptions == null))
                {
                    _Subscriptions = base.CreateObjectSet<Subscription>("Subscriptions");
                }
                return _Subscriptions;
            }
        }
        private ObjectSet<Subscription> _Subscriptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Win> Wins
        {
            get
            {
                if ((_Wins == null))
                {
                    _Wins = base.CreateObjectSet<Win>("Wins");
                }
                return _Wins;
            }
        }
        private ObjectSet<Win> _Wins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Config> Configs
        {
            get
            {
                if ((_Configs == null))
                {
                    _Configs = base.CreateObjectSet<Config>("Configs");
                }
                return _Configs;
            }
        }
        private ObjectSet<Config> _Configs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Setting> Settings
        {
            get
            {
                if ((_Settings == null))
                {
                    _Settings = base.CreateObjectSet<Setting>("Settings");
                }
                return _Settings;
            }
        }
        private ObjectSet<Setting> _Settings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Document> Documents
        {
            get
            {
                if ((_Documents == null))
                {
                    _Documents = base.CreateObjectSet<Document>("Documents");
                }
                return _Documents;
            }
        }
        private ObjectSet<Document> _Documents;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Archives EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArchives(Archive archive)
        {
            base.AddObject("Archives", archive);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Boards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBoards(Board board)
        {
            base.AddObject("Boards", board);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Setups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSetups(Setup setup)
        {
            base.AddObject("Setups", setup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subscriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubscriptions(Subscription subscription)
        {
            base.AddObject("Subscriptions", subscription);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Wins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWins(Win win)
        {
            base.AddObject("Wins", win);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Configs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConfigs(Config config)
        {
            base.AddObject("Configs", config);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Settings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSettings(Setting setting)
        {
            base.AddObject("Settings", setting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Documents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDocuments(Document document)
        {
            base.AddObject("Documents", document);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Archive")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Archive : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Archive object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Archive CreateArchive(global::System.Int64 id)
        {
            Archive archive = new Archive();
            archive.id = id;
            return archive;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game
        {
            get
            {
                return _game;
            }
            set
            {
                OngameChanging(value);
                ReportPropertyChanging("game");
                _game = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("game");
                OngameChanged();
            }
        }
        private global::System.String _game;
        partial void OngameChanging(global::System.String value);
        partial void OngameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> gamedate
        {
            get
            {
                return _gamedate;
            }
            set
            {
                OngamedateChanging(value);
                ReportPropertyChanging("gamedate");
                _gamedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gamedate");
                OngamedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _gamedate;
        partial void OngamedateChanging(Nullable<global::System.DateTime> value);
        partial void OngamedateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] webpage
        {
            get
            {
                return StructuralObject.GetValidValue(_webpage);
            }
            set
            {
                OnwebpageChanging(value);
                ReportPropertyChanging("webpage");
                _webpage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("webpage");
                OnwebpageChanged();
            }
        }
        private global::System.Byte[] _webpage;
        partial void OnwebpageChanging(global::System.Byte[] value);
        partial void OnwebpageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdby
        {
            get
            {
                return _createdby;
            }
            set
            {
                OncreatedbyChanging(value);
                ReportPropertyChanging("createdby");
                _createdby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdby");
                OncreatedbyChanged();
            }
        }
        private global::System.String _createdby;
        partial void OncreatedbyChanging(global::System.String value);
        partial void OncreatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedby
        {
            get
            {
                return _modifiedby;
            }
            set
            {
                OnmodifiedbyChanging(value);
                ReportPropertyChanging("modifiedby");
                _modifiedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedby");
                OnmodifiedbyChanged();
            }
        }
        private global::System.String _modifiedby;
        partial void OnmodifiedbyChanging(global::System.String value);
        partial void OnmodifiedbyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Board")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Board : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Board object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Board CreateBoard(global::System.Int64 id)
        {
            Board board = new Board();
            board.id = id;
            return board;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private Nullable<global::System.Int64> _userid;
        partial void OnuseridChanging(Nullable<global::System.Int64> value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> scriptid
        {
            get
            {
                return _scriptid;
            }
            set
            {
                OnscriptidChanging(value);
                ReportPropertyChanging("scriptid");
                _scriptid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("scriptid");
                OnscriptidChanged();
            }
        }
        private Nullable<global::System.Int64> _scriptid;
        partial void OnscriptidChanging(Nullable<global::System.Int64> value);
        partial void OnscriptidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> boardnr
        {
            get
            {
                return _boardnr;
            }
            set
            {
                OnboardnrChanging(value);
                ReportPropertyChanging("boardnr");
                _boardnr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("boardnr");
                OnboardnrChanged();
            }
        }
        private Nullable<global::System.Int64> _boardnr;
        partial void OnboardnrChanging(Nullable<global::System.Int64> value);
        partial void OnboardnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b1
        {
            get
            {
                return _b1;
            }
            set
            {
                Onb1Changing(value);
                ReportPropertyChanging("b1");
                _b1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b1");
                Onb1Changed();
            }
        }
        private Nullable<global::System.Int64> _b1;
        partial void Onb1Changing(Nullable<global::System.Int64> value);
        partial void Onb1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b2
        {
            get
            {
                return _b2;
            }
            set
            {
                Onb2Changing(value);
                ReportPropertyChanging("b2");
                _b2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b2");
                Onb2Changed();
            }
        }
        private Nullable<global::System.Int64> _b2;
        partial void Onb2Changing(Nullable<global::System.Int64> value);
        partial void Onb2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b3
        {
            get
            {
                return _b3;
            }
            set
            {
                Onb3Changing(value);
                ReportPropertyChanging("b3");
                _b3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b3");
                Onb3Changed();
            }
        }
        private Nullable<global::System.Int64> _b3;
        partial void Onb3Changing(Nullable<global::System.Int64> value);
        partial void Onb3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b4
        {
            get
            {
                return _b4;
            }
            set
            {
                Onb4Changing(value);
                ReportPropertyChanging("b4");
                _b4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b4");
                Onb4Changed();
            }
        }
        private Nullable<global::System.Int64> _b4;
        partial void Onb4Changing(Nullable<global::System.Int64> value);
        partial void Onb4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b5
        {
            get
            {
                return _b5;
            }
            set
            {
                Onb5Changing(value);
                ReportPropertyChanging("b5");
                _b5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b5");
                Onb5Changed();
            }
        }
        private Nullable<global::System.Int64> _b5;
        partial void Onb5Changing(Nullable<global::System.Int64> value);
        partial void Onb5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b6
        {
            get
            {
                return _b6;
            }
            set
            {
                Onb6Changing(value);
                ReportPropertyChanging("b6");
                _b6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b6");
                Onb6Changed();
            }
        }
        private Nullable<global::System.Int64> _b6;
        partial void Onb6Changing(Nullable<global::System.Int64> value);
        partial void Onb6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Config")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Config : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Config object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Config CreateConfig(global::System.Int64 id)
        {
            Config config = new Config();
            config.id = id;
            return config;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game
        {
            get
            {
                return _game;
            }
            set
            {
                OngameChanging(value);
                ReportPropertyChanging("game");
                _game = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("game");
                OngameChanged();
            }
        }
        private global::System.String _game;
        partial void OngameChanging(global::System.String value);
        partial void OngameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String webpage
        {
            get
            {
                return _webpage;
            }
            set
            {
                OnwebpageChanging(value);
                ReportPropertyChanging("webpage");
                _webpage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("webpage");
                OnwebpageChanged();
            }
        }
        private global::System.String _webpage;
        partial void OnwebpageChanging(global::System.String value);
        partial void OnwebpageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdby
        {
            get
            {
                return _createdby;
            }
            set
            {
                OncreatedbyChanging(value);
                ReportPropertyChanging("createdby");
                _createdby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdby");
                OncreatedbyChanged();
            }
        }
        private global::System.String _createdby;
        partial void OncreatedbyChanging(global::System.String value);
        partial void OncreatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedby
        {
            get
            {
                return _modifiedby;
            }
            set
            {
                OnmodifiedbyChanging(value);
                ReportPropertyChanging("modifiedby");
                _modifiedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedby");
                OnmodifiedbyChanged();
            }
        }
        private global::System.String _modifiedby;
        partial void OnmodifiedbyChanging(global::System.String value);
        partial void OnmodifiedbyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Document")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Document : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Document object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Document CreateDocument(global::System.Int64 id)
        {
            Document document = new Document();
            document.id = id;
            return document;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> doccatid
        {
            get
            {
                return _doccatid;
            }
            set
            {
                OndoccatidChanging(value);
                ReportPropertyChanging("doccatid");
                _doccatid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("doccatid");
                OndoccatidChanged();
            }
        }
        private Nullable<global::System.Int64> _doccatid;
        partial void OndoccatidChanging(Nullable<global::System.Int64> value);
        partial void OndoccatidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> doctypeid
        {
            get
            {
                return _doctypeid;
            }
            set
            {
                OndoctypeidChanging(value);
                ReportPropertyChanging("doctypeid");
                _doctypeid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("doctypeid");
                OndoctypeidChanged();
            }
        }
        private Nullable<global::System.Int64> _doctypeid;
        partial void OndoctypeidChanging(Nullable<global::System.Int64> value);
        partial void OndoctypeidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ext
        {
            get
            {
                return _ext;
            }
            set
            {
                OnextChanging(value);
                ReportPropertyChanging("ext");
                _ext = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ext");
                OnextChanged();
            }
        }
        private global::System.String _ext;
        partial void OnextChanging(global::System.String value);
        partial void OnextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private Nullable<global::System.Int64> _size;
        partial void OnsizeChanging(Nullable<global::System.Int64> value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] docfile
        {
            get
            {
                return StructuralObject.GetValidValue(_docfile);
            }
            set
            {
                OndocfileChanging(value);
                ReportPropertyChanging("docfile");
                _docfile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("docfile");
                OndocfileChanged();
            }
        }
        private global::System.Byte[] _docfile;
        partial void OndocfileChanging(global::System.Byte[] value);
        partial void OndocfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdby
        {
            get
            {
                return _createdby;
            }
            set
            {
                OncreatedbyChanging(value);
                ReportPropertyChanging("createdby");
                _createdby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdby");
                OncreatedbyChanged();
            }
        }
        private global::System.String _createdby;
        partial void OncreatedbyChanging(global::System.String value);
        partial void OncreatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedby
        {
            get
            {
                return _modifiedby;
            }
            set
            {
                OnmodifiedbyChanging(value);
                ReportPropertyChanging("modifiedby");
                _modifiedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedby");
                OnmodifiedbyChanged();
            }
        }
        private global::System.String _modifiedby;
        partial void OnmodifiedbyChanging(global::System.String value);
        partial void OnmodifiedbyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setting object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Setting CreateSetting(global::System.Int64 id)
        {
            Setting setting = new Setting();
            setting.id = id;
            return setting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdby
        {
            get
            {
                return _createdby;
            }
            set
            {
                OncreatedbyChanging(value);
                ReportPropertyChanging("createdby");
                _createdby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdby");
                OncreatedbyChanged();
            }
        }
        private global::System.String _createdby;
        partial void OncreatedbyChanging(global::System.String value);
        partial void OncreatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedby
        {
            get
            {
                return _modifiedby;
            }
            set
            {
                OnmodifiedbyChanging(value);
                ReportPropertyChanging("modifiedby");
                _modifiedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedby");
                OnmodifiedbyChanged();
            }
        }
        private global::System.String _modifiedby;
        partial void OnmodifiedbyChanging(global::System.String value);
        partial void OnmodifiedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Setup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Setup object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Setup CreateSetup(global::System.Int64 id)
        {
            Setup setup = new Setup();
            setup.id = id;
            return setup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game
        {
            get
            {
                return _game;
            }
            set
            {
                OngameChanging(value);
                ReportPropertyChanging("game");
                _game = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("game");
                OngameChanged();
            }
        }
        private global::System.String _game;
        partial void OngameChanging(global::System.String value);
        partial void OngameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String webpage
        {
            get
            {
                return _webpage;
            }
            set
            {
                OnwebpageChanging(value);
                ReportPropertyChanging("webpage");
                _webpage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("webpage");
                OnwebpageChanged();
            }
        }
        private global::System.String _webpage;
        partial void OnwebpageChanging(global::System.String value);
        partial void OnwebpageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdby
        {
            get
            {
                return _createdby;
            }
            set
            {
                OncreatedbyChanging(value);
                ReportPropertyChanging("createdby");
                _createdby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdby");
                OncreatedbyChanged();
            }
        }
        private global::System.String _createdby;
        partial void OncreatedbyChanging(global::System.String value);
        partial void OncreatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedby
        {
            get
            {
                return _modifiedby;
            }
            set
            {
                OnmodifiedbyChanging(value);
                ReportPropertyChanging("modifiedby");
                _modifiedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedby");
                OnmodifiedbyChanged();
            }
        }
        private global::System.String _modifiedby;
        partial void OnmodifiedbyChanging(global::System.String value);
        partial void OnmodifiedbyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Subscription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subscription : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subscription object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Subscription CreateSubscription(global::System.Int64 id)
        {
            Subscription subscription = new Subscription();
            subscription.id = id;
            return subscription;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private Nullable<global::System.Int64> _userid;
        partial void OnuseridChanging(Nullable<global::System.Int64> value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String scriptnr
        {
            get
            {
                return _scriptnr;
            }
            set
            {
                OnscriptnrChanging(value);
                ReportPropertyChanging("scriptnr");
                _scriptnr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("scriptnr");
                OnscriptnrChanged();
            }
        }
        private global::System.String _scriptnr;
        partial void OnscriptnrChanging(global::System.String value);
        partial void OnscriptnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game
        {
            get
            {
                return _game;
            }
            set
            {
                OngameChanging(value);
                ReportPropertyChanging("game");
                _game = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("game");
                OngameChanged();
            }
        }
        private global::System.String _game;
        partial void OngameChanging(global::System.String value);
        partial void OngameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> startdate
        {
            get
            {
                return _startdate;
            }
            set
            {
                OnstartdateChanging(value);
                ReportPropertyChanging("startdate");
                _startdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startdate");
                OnstartdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _startdate;
        partial void OnstartdateChanging(Nullable<global::System.DateTime> value);
        partial void OnstartdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> enddate
        {
            get
            {
                return _enddate;
            }
            set
            {
                OnenddateChanging(value);
                ReportPropertyChanging("enddate");
                _enddate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("enddate");
                OnenddateChanged();
            }
        }
        private Nullable<global::System.DateTime> _enddate;
        partial void OnenddateChanging(Nullable<global::System.DateTime> value);
        partial void OnenddateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> numboards
        {
            get
            {
                return _numboards;
            }
            set
            {
                OnnumboardsChanging(value);
                ReportPropertyChanging("numboards");
                _numboards = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numboards");
                OnnumboardsChanged();
            }
        }
        private Nullable<global::System.Int64> _numboards;
        partial void OnnumboardsChanging(Nullable<global::System.Int64> value);
        partial void OnnumboardsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> inclplus
        {
            get
            {
                return _inclplus;
            }
            set
            {
                OninclplusChanging(value);
                ReportPropertyChanging("inclplus");
                _inclplus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inclplus");
                OninclplusChanged();
            }
        }
        private Nullable<global::System.Boolean> _inclplus;
        partial void OninclplusChanging(Nullable<global::System.Boolean> value);
        partial void OninclplusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LottoDBModel", Name="Win")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Win : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Win object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Win CreateWin(global::System.Int64 id)
        {
            Win win = new Win();
            win.id = id;
            return win;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String scriptnr
        {
            get
            {
                return _scriptnr;
            }
            set
            {
                OnscriptnrChanging(value);
                ReportPropertyChanging("scriptnr");
                _scriptnr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("scriptnr");
                OnscriptnrChanged();
            }
        }
        private global::System.String _scriptnr;
        partial void OnscriptnrChanging(global::System.String value);
        partial void OnscriptnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> scriptid
        {
            get
            {
                return _scriptid;
            }
            set
            {
                OnscriptidChanging(value);
                ReportPropertyChanging("scriptid");
                _scriptid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("scriptid");
                OnscriptidChanged();
            }
        }
        private Nullable<global::System.Int64> _scriptid;
        partial void OnscriptidChanging(Nullable<global::System.Int64> value);
        partial void OnscriptidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> boardnr
        {
            get
            {
                return _boardnr;
            }
            set
            {
                OnboardnrChanging(value);
                ReportPropertyChanging("boardnr");
                _boardnr = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("boardnr");
                OnboardnrChanged();
            }
        }
        private Nullable<global::System.Int64> _boardnr;
        partial void OnboardnrChanging(Nullable<global::System.Int64> value);
        partial void OnboardnrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> gamedate
        {
            get
            {
                return _gamedate;
            }
            set
            {
                OngamedateChanging(value);
                ReportPropertyChanging("gamedate");
                _gamedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gamedate");
                OngamedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _gamedate;
        partial void OngamedateChanging(Nullable<global::System.DateTime> value);
        partial void OngamedateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game
        {
            get
            {
                return _game;
            }
            set
            {
                OngameChanging(value);
                ReportPropertyChanging("game");
                _game = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("game");
                OngameChanged();
            }
        }
        private global::System.String _game;
        partial void OngameChanging(global::System.String value);
        partial void OngameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> w1
        {
            get
            {
                return _w1;
            }
            set
            {
                Onw1Changing(value);
                ReportPropertyChanging("w1");
                _w1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("w1");
                Onw1Changed();
            }
        }
        private Nullable<global::System.Int64> _w1;
        partial void Onw1Changing(Nullable<global::System.Int64> value);
        partial void Onw1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> w2
        {
            get
            {
                return _w2;
            }
            set
            {
                Onw2Changing(value);
                ReportPropertyChanging("w2");
                _w2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("w2");
                Onw2Changed();
            }
        }
        private Nullable<global::System.Int64> _w2;
        partial void Onw2Changing(Nullable<global::System.Int64> value);
        partial void Onw2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> w3
        {
            get
            {
                return _w3;
            }
            set
            {
                Onw3Changing(value);
                ReportPropertyChanging("w3");
                _w3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("w3");
                Onw3Changed();
            }
        }
        private Nullable<global::System.Int64> _w3;
        partial void Onw3Changing(Nullable<global::System.Int64> value);
        partial void Onw3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> w4
        {
            get
            {
                return _w4;
            }
            set
            {
                Onw4Changing(value);
                ReportPropertyChanging("w4");
                _w4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("w4");
                Onw4Changed();
            }
        }
        private Nullable<global::System.Int64> _w4;
        partial void Onw4Changing(Nullable<global::System.Int64> value);
        partial void Onw4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> w5
        {
            get
            {
                return _w5;
            }
            set
            {
                Onw5Changing(value);
                ReportPropertyChanging("w5");
                _w5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("w5");
                Onw5Changed();
            }
        }
        private Nullable<global::System.Int64> _w5;
        partial void Onw5Changing(Nullable<global::System.Int64> value);
        partial void Onw5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> w6
        {
            get
            {
                return _w6;
            }
            set
            {
                Onw6Changing(value);
                ReportPropertyChanging("w6");
                _w6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("w6");
                Onw6Changed();
            }
        }
        private Nullable<global::System.Int64> _w6;
        partial void Onw6Changing(Nullable<global::System.Int64> value);
        partial void Onw6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> b
        {
            get
            {
                return _b;
            }
            set
            {
                OnbChanging(value);
                ReportPropertyChanging("b");
                _b = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("b");
                OnbChanged();
            }
        }
        private Nullable<global::System.Int64> _b;
        partial void OnbChanging(Nullable<global::System.Int64> value);
        partial void OnbChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> p1
        {
            get
            {
                return _p1;
            }
            set
            {
                Onp1Changing(value);
                ReportPropertyChanging("p1");
                _p1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("p1");
                Onp1Changed();
            }
        }
        private Nullable<global::System.Int64> _p1;
        partial void Onp1Changing(Nullable<global::System.Int64> value);
        partial void Onp1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> p2
        {
            get
            {
                return _p2;
            }
            set
            {
                Onp2Changing(value);
                ReportPropertyChanging("p2");
                _p2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("p2");
                Onp2Changed();
            }
        }
        private Nullable<global::System.Int64> _p2;
        partial void Onp2Changing(Nullable<global::System.Int64> value);
        partial void Onp2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> p3
        {
            get
            {
                return _p3;
            }
            set
            {
                Onp3Changing(value);
                ReportPropertyChanging("p3");
                _p3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("p3");
                Onp3Changed();
            }
        }
        private Nullable<global::System.Int64> _p3;
        partial void Onp3Changing(Nullable<global::System.Int64> value);
        partial void Onp3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> p4
        {
            get
            {
                return _p4;
            }
            set
            {
                Onp4Changing(value);
                ReportPropertyChanging("p4");
                _p4 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("p4");
                Onp4Changed();
            }
        }
        private Nullable<global::System.Int64> _p4;
        partial void Onp4Changing(Nullable<global::System.Int64> value);
        partial void Onp4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> p5
        {
            get
            {
                return _p5;
            }
            set
            {
                Onp5Changing(value);
                ReportPropertyChanging("p5");
                _p5 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("p5");
                Onp5Changed();
            }
        }
        private Nullable<global::System.Int64> _p5;
        partial void Onp5Changing(Nullable<global::System.Int64> value);
        partial void Onp5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> p6
        {
            get
            {
                return _p6;
            }
            set
            {
                Onp6Changing(value);
                ReportPropertyChanging("p6");
                _p6 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("p6");
                Onp6Changed();
            }
        }
        private Nullable<global::System.Int64> _p6;
        partial void Onp6Changing(Nullable<global::System.Int64> value);
        partial void Onp6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String division
        {
            get
            {
                return _division;
            }
            set
            {
                OndivisionChanging(value);
                ReportPropertyChanging("division");
                _division = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("division");
                OndivisionChanged();
            }
        }
        private global::System.String _division;
        partial void OndivisionChanging(global::System.String value);
        partial void OndivisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> earning
        {
            get
            {
                return _earning;
            }
            set
            {
                OnearningChanging(value);
                ReportPropertyChanging("earning");
                _earning = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("earning");
                OnearningChanged();
            }
        }
        private Nullable<global::System.Double> _earning;
        partial void OnearningChanging(Nullable<global::System.Double> value);
        partial void OnearningChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] webimage
        {
            get
            {
                return StructuralObject.GetValidValue(_webimage);
            }
            set
            {
                OnwebimageChanging(value);
                ReportPropertyChanging("webimage");
                _webimage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("webimage");
                OnwebimageChanged();
            }
        }
        private global::System.Byte[] _webimage;
        partial void OnwebimageChanging(global::System.Byte[] value);
        partial void OnwebimageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> active
        {
            get
            {
                return _active;
            }
            set
            {
                OnactiveChanging(value);
                ReportPropertyChanging("active");
                _active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("active");
                OnactiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _active;
        partial void OnactiveChanging(Nullable<global::System.Boolean> value);
        partial void OnactiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdon;
        partial void OncreatedonChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedon
        {
            get
            {
                return _modifiedon;
            }
            set
            {
                OnmodifiedonChanging(value);
                ReportPropertyChanging("modifiedon");
                _modifiedon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedon");
                OnmodifiedonChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedon;
        partial void OnmodifiedonChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String createdby
        {
            get
            {
                return _createdby;
            }
            set
            {
                OncreatedbyChanging(value);
                ReportPropertyChanging("createdby");
                _createdby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("createdby");
                OncreatedbyChanged();
            }
        }
        private global::System.String _createdby;
        partial void OncreatedbyChanging(global::System.String value);
        partial void OncreatedbyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String modifiedby
        {
            get
            {
                return _modifiedby;
            }
            set
            {
                OnmodifiedbyChanging(value);
                ReportPropertyChanging("modifiedby");
                _modifiedby = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("modifiedby");
                OnmodifiedbyChanged();
            }
        }
        private global::System.String _modifiedby;
        partial void OnmodifiedbyChanging(global::System.String value);
        partial void OnmodifiedbyChanged();

        #endregion
    
    }

    #endregion
    
}
