//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ttpim.gamemodule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ttpim.gamemodule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap animated_loading {
            get {
                object obj = ResourceManager.GetObject("animated_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ball_27 {
            get {
                object obj = ResourceManager.GetObject("ball_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap balloon_star {
            get {
                object obj = ResourceManager.GetObject("balloon_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonus_24x24 {
            get {
                object obj = ResourceManager.GetObject("bonus_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonushead {
            get {
                object obj = ResourceManager.GetObject("bonushead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonusmatch {
            get {
                object obj = ResourceManager.GetObject("bonusmatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bonusmatch_32 {
            get {
                object obj = ResourceManager.GetObject("bonusmatch_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap caution {
            get {
                object obj = ResourceManager.GetObject("caution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clown_happy {
            get {
                object obj = ResourceManager.GetObject("clown_happy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clown_unhappy {
            get {
                object obj = ResourceManager.GetObject("clown_unhappy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap coinstash {
            get {
                object obj = ResourceManager.GetObject("coinstash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connected {
            get {
                object obj = ResourceManager.GetObject("connected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connected_x {
            get {
                object obj = ResourceManager.GetObject("connected-x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connected_y {
            get {
                object obj = ResourceManager.GetObject("connected-y", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connected1 {
            get {
                object obj = ResourceManager.GetObject("connected1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connected3 {
            get {
                object obj = ResourceManager.GetObject("connected3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap continuetowork {
            get {
                object obj = ResourceManager.GetObject("continuetowork", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crossmark {
            get {
                object obj = ResourceManager.GetObject("crossmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap crying {
            get {
                object obj = ResourceManager.GetObject("crying", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap database_ok {
            get {
                object obj = ResourceManager.GetObject("database_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap db {
            get {
                object obj = ResourceManager.GetObject("db", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div1 {
            get {
                object obj = ResourceManager.GetObject("div1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div1head {
            get {
                object obj = ResourceManager.GetObject("div1head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div2 {
            get {
                object obj = ResourceManager.GetObject("div2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div2head {
            get {
                object obj = ResourceManager.GetObject("div2head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div3 {
            get {
                object obj = ResourceManager.GetObject("div3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div3head {
            get {
                object obj = ResourceManager.GetObject("div3head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div4 {
            get {
                object obj = ResourceManager.GetObject("div4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div4head {
            get {
                object obj = ResourceManager.GetObject("div4head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div5 {
            get {
                object obj = ResourceManager.GetObject("div5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div5head {
            get {
                object obj = ResourceManager.GetObject("div5head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div6 {
            get {
                object obj = ResourceManager.GetObject("div6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div6head {
            get {
                object obj = ResourceManager.GetObject("div6head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div7 {
            get {
                object obj = ResourceManager.GetObject("div7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div71 {
            get {
                object obj = ResourceManager.GetObject("div71", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div72 {
            get {
                object obj = ResourceManager.GetObject("div72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div7head {
            get {
                object obj = ResourceManager.GetObject("div7head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div8 {
            get {
                object obj = ResourceManager.GetObject("div8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div81 {
            get {
                object obj = ResourceManager.GetObject("div81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div82 {
            get {
                object obj = ResourceManager.GetObject("div82", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap div8head {
            get {
                object obj = ResourceManager.GetObject("div8head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_database_24 {
            get {
                object obj = ResourceManager.GetObject("error_database_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap getlatest_3 {
            get {
                object obj = ResourceManager.GetObject("getlatest_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gold_dice {
            get {
                object obj = ResourceManager.GetObject("gold-dice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap greenstrip {
            get {
                object obj = ResourceManager.GetObject("greenstrip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_ball1 {
            get {
                object obj = ResourceManager.GetObject("h_ball1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_ball2 {
            get {
                object obj = ResourceManager.GetObject("h_ball2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_ball3 {
            get {
                object obj = ResourceManager.GetObject("h_ball3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_ball4 {
            get {
                object obj = ResourceManager.GetObject("h_ball4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_ball5 {
            get {
                object obj = ResourceManager.GetObject("h_ball5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_ball6 {
            get {
                object obj = ResourceManager.GetObject("h_ball6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_bonus {
            get {
                object obj = ResourceManager.GetObject("h_bonus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h_powerball {
            get {
                object obj = ResourceManager.GetObject("h_powerball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_ball1 {
            get {
                object obj = ResourceManager.GetObject("hd_ball1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_ball2 {
            get {
                object obj = ResourceManager.GetObject("hd_ball2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_ball3 {
            get {
                object obj = ResourceManager.GetObject("hd_ball3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_ball4 {
            get {
                object obj = ResourceManager.GetObject("hd_ball4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_ball5 {
            get {
                object obj = ResourceManager.GetObject("hd_ball5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_ball6 {
            get {
                object obj = ResourceManager.GetObject("hd_ball6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_bonus_3 {
            get {
                object obj = ResourceManager.GetObject("hd_bonus_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_bonus4 {
            get {
                object obj = ResourceManager.GetObject("hd_bonus4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_powerball2 {
            get {
                object obj = ResourceManager.GetObject("hd_powerball2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_powerball3 {
            get {
                object obj = ResourceManager.GetObject("hd_powerball3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_powerball4 {
            get {
                object obj = ResourceManager.GetObject("hd_powerball4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_powerball5 {
            get {
                object obj = ResourceManager.GetObject("hd_powerball5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hd_winningnumbers {
            get {
                object obj = ResourceManager.GetObject("hd_winningnumbers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap jackpot {
            get {
                object obj = ResourceManager.GetObject("jackpot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap jackpot1 {
            get {
                object obj = ResourceManager.GetObject("jackpot1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap jackpothead {
            get {
                object obj = ResourceManager.GetObject("jackpothead", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap latest_blue {
            get {
                object obj = ResourceManager.GetObject("latest_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap latest_gray {
            get {
                object obj = ResourceManager.GetObject("latest_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap latest_gray2 {
            get {
                object obj = ResourceManager.GetObject("latest_gray2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lottologgo {
            get {
                object obj = ResourceManager.GetObject("lottologgo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lottoPlus_top_right_home {
            get {
                object obj = ResourceManager.GetObject("lottoPlus_top_right_home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap messagebase {
            get {
                object obj = ResourceManager.GetObject("messagebase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moneyjar {
            get {
                object obj = ResourceManager.GetObject("moneyjar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moneystash {
            get {
                object obj = ResourceManager.GetObject("moneystash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap national_lottery {
            get {
                object obj = ResourceManager.GetObject("national_lottery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdgirl {
            get {
                object obj = ResourceManager.GetObject("nerdgirl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nerdi {
            get {
                object obj = ResourceManager.GetObject("Nerdi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_boy1 {
            get {
                object obj = ResourceManager.GetObject("nerdi_boy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_girl2 {
            get {
                object obj = ResourceManager.GetObject("nerdi_girl2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_girl3 {
            get {
                object obj = ResourceManager.GetObject("nerdi_girl3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_girl4 {
            get {
                object obj = ResourceManager.GetObject("nerdi_girl4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_girl5 {
            get {
                object obj = ResourceManager.GetObject("nerdi_girl5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_glasses2 {
            get {
                object obj = ResourceManager.GetObject("nerdi_glasses2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_glasses21 {
            get {
                object obj = ResourceManager.GetObject("nerdi_glasses21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_glasses3 {
            get {
                object obj = ResourceManager.GetObject("nerdi_glasses3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_glasses4 {
            get {
                object obj = ResourceManager.GetObject("nerdi_glasses4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_glasses5 {
            get {
                object obj = ResourceManager.GetObject("nerdi_glasses5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_no1 {
            get {
                object obj = ResourceManager.GetObject("nerdi_no1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_no2 {
            get {
                object obj = ResourceManager.GetObject("nerdi_no2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_no3 {
            get {
                object obj = ResourceManager.GetObject("nerdi_no3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdi_no4 {
            get {
                object obj = ResourceManager.GetObject("nerdi_no4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdread {
            get {
                object obj = ResourceManager.GetObject("nerdread", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdspecs {
            get {
                object obj = ResourceManager.GetObject("nerdspecs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nerdthumbsup {
            get {
                object obj = ResourceManager.GetObject("nerdthumbsup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nobonus {
            get {
                object obj = ResourceManager.GetObject("nobonus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nointernet {
            get {
                object obj = ResourceManager.GetObject("nointernet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nointernet2 {
            get {
                object obj = ResourceManager.GetObject("nointernet2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nointernet3 {
            get {
                object obj = ResourceManager.GetObject("nointernet3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap okmark {
            get {
                object obj = ResourceManager.GetObject("okmark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retry {
            get {
                object obj = ResourceManager.GetObject("retry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retry2 {
            get {
                object obj = ResourceManager.GetObject("retry2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap retry4 {
            get {
                object obj = ResourceManager.GetObject("retry4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap splashscreen2 {
            get {
                object obj = ResourceManager.GetObject("splashscreen2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap win_24x24 {
            get {
                object obj = ResourceManager.GetObject("win_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap winboard {
            get {
                object obj = ResourceManager.GetObject("winboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap winboard_32 {
            get {
                object obj = ResourceManager.GetObject("winboard_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap winningnums_3 {
            get {
                object obj = ResourceManager.GetObject("winningnums_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap winnumbers4 {
            get {
                object obj = ResourceManager.GetObject("winnumbers4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap workoffline3 {
            get {
                object obj = ResourceManager.GetObject("workoffline3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap youwin {
            get {
                object obj = ResourceManager.GetObject("youwin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
